#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Ubuntu)
      $NOSUDO sudo aptitude install -y git g++ cmake make libcurl4-openssl-dev libboost-filesystem-dev libboost-system-dev libboost-chrono-dev libboost-program-options-dev libboost-thread-dev libcrypto++-dev libssl-dev libfuse-dev python
      mkdir -p "$shome/vendor"
      rm -rf "$shome/vendor/cryfs-${CRYFS_VERSION}"
      git clone https://github.com/cryfs/cryfs.git "$shome/vendor/cryfs-${CRYFS_VERSION}"
      cd "$shome/vendor/cryfs-${CRYFS_VERSION}"
      git checkout "${CRYFS_VERSION}"
      mkdir cmake
      cd cmake
      cmake ..
      make
      mkdir -p "$shome/bin"
      chmod 755 src/cryfs-cli/cryfs
      rsync -ia src/cryfs-cli/cryfs "$shome/bin/"
      rm -rf "$shome/vendor/cryfs-${CRYFS_VERSION}"
      ;;
    Darwin)
      brew instal cryfs
      ;;
  esac
}

main "$@"
