#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  curl -O "https://s3-eu-west-1.amazonaws.com/apt.cryfs.org/ubuntu/pool/main/c/cryfs/cryfs_0.9.7_ubuntu-16.04-x64.deb"
  $NOSUDO sudo dpkg -i cryfs_0.9.7_ubuntu-16.04-x64.deb
  rm -f cryfs_0.9.7_ubuntu-16.04-x64.deb
}

main "$@"
