#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Ubuntu|Darwin)
      true
      ;;
    *)
      return 0
      ;;
  esac

  if [[ "$($shome/script/version | jq -r '.cryfs')" != "$CRYFS_VERSION" ]]; then
    return 1
  fi

  return 0
}

main "$@"
