#!/usr/bin/env bash

function _cryfs_profile {
  local shome="${_cryfs_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  export CRYFS_FRONTEND=noninteractive
  export CRYFS_NO_UPDATE_CHECK=true
}

_cryfs_profile
