#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_cryfs="0.0.1"
  jq -n --arg cryfs "$ver_cryfs" '{cryfs: $cryfs}'
}

version "$@"
